BookTable/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookTable.Database;
using BookTable.Models.DatabaseModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;


namespace BookTable.Controllers
{
    public class RestaurantsController : Controller
    {
        private ApplicationUserManager _userManager;

        public RestaurantsController()
        {
        }

        public RestaurantsController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private BookTableContext db = new BookTableContext();

        // GET: Restaurants
        [Authorize(Roles = "User,Admin,Restaurant")]
        public ActionResult Index()
        {
            List<Restaurant> restaurant = new List<Restaurant>();

            var user = UserManager.FindById(User.Identity.GetUserId());
            var restaurantUser = UserManager.IsInRole(user.Id, "Restaurant");

            if(restaurantUser)
            {
                return View(db.Restaurants.Where(rest => rest.OwnerId == user.Id).ToList());
            }
           
            return View(db.Restaurants.ToList());
        }

        // GET: Restaurants/Details/5
        [Authorize(Roles = "User,Admin,Restaurant")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // GET: Restaurants/Create
        [Authorize(Roles = "Admin,Restaurant")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Restaurant")]
        public ActionResult Create([Bind(Include = "RestaurantId,Name,Category,Description,Address")] Restaurant restaurant)
        {
            

            var user = UserManager.FindById(User.Identity.GetUserId());
            string ownID = user.Id;

            if (ModelState.IsValid && ownID.Length > 0)
            {
                restaurant.OwnerId = ownID;
                db.Restaurants.Add(restaurant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        [Authorize(Roles = "Admin,Restaurant")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Restaurant")]
        public ActionResult Edit([Bind(Include = "RestaurantId,OwnerId,Name,Category,Description,Address")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurant);
        }

        // GET: Restaurants/Delete/5
        [Authorize(Roles = "Admin,Restaurant")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }

            List<Table> tablesRest = db.Tables.Include(t => t.Restaurant).Where(t => t.Restaurant.RestaurantId == id).ToList();

            foreach (Table tab in tablesRest)
            {
                db.Tables.Remove(db.Tables.Find(tab.TableId));
            }

            try
            {
                var reservations = db.Reservations.Include(r => r.Table)
                    .Include(r => r.Event).Where(r => r.Table.Restaurant.RestaurantId == restaurant.RestaurantId).ToList();
                bool canDelete = true;
                foreach(Reservation r in reservations)
                {
                    if(r.Event.Date > DateTime.Now)
                    {
                        canDelete = false;
                    }
                }

                if(canDelete)
                {

                    foreach(Reservation r in reservations)
                    {
                        db.Reservations.Remove(db.Reservations.Find(r.ReservationId));
                    }

                    db.Restaurants.Remove(restaurant);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                } else
                {
                    return RedirectToAction("deleteFailed");
                }

               
            }
            catch(Exception e)
            {
                return RedirectToAction("deleteFailed"); ;
            }

        }

        //GET:
        public ActionResult deleteFailed()
        {
            return View();
        }


        // POST: Restaurants/Delete/5
        [Authorize(Roles = "Admin,Restaurant")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.Restaurants.Find(id);

            return View();
           
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BookTable/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book a table</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/fontawesome")
    @RenderSection("head", required: false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>
</head>
<body>
    <nav style="background-color: rgba(0,0,0,0.7)" class="navbar navbar-expand-md fixed-top navbar-dark">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--<a href="/Home/Index" class="navbar-brand mr-5"><img src="~/Assets/logo.png"></a>-->
            @Html.ActionLink("Book a Table", "Index", "Home", new { area = "" }, new { @class = "navbar-brand mr" })
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    <li class="nav-item">@Html.ActionLink("Events", "Index", "Events", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    @if (User.IsInRole("Restaurant"))
                    {
                        <li class="nav-item">@Html.ActionLink("My Restaurant", "Index", "Restaurants", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    }

                    @if (User.IsInRole("Restaurant"))
                    {
                        <li class="nav-item">@Html.ActionLink("My Events", "editingEvents", "Events", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    }

                    @if (User.IsInRole("Restaurant") || User.IsInRole("User") || User.IsInRole("Admin"))
                    {
                        <li class="nav-item">@Html.ActionLink("Reservations", "Index", "Reservations", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">@Html.ActionLink("Users", "Index", "Account", new { area = "" }, new { @class = "nav-link text-white" })</li>
                        <li class="nav-item">@Html.ActionLink("Restaurants", "Index", "Restaurants", new { area = "" }, new { @class = "nav-link text-white" })</li>
                        <li class="nav-item">@Html.ActionLink("Add Role", "AddUserToRole", "Account", new { area = "" }, new { @class = "nav-link text-white" })</li>
                    }



                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div style="margin-bottom: 30px">

    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="float-right">&copy; @DateTime.Now.Year - Book a table</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>