BookTable/Models/ViewModels/TablesToBook.cs
using BookTable.Models.DatabaseModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookTable.Models.ViewModels
{
    public class TablesToBook
    {
        public Restaurant restaurant { get; set; }
        public List<Table> tables { get; set; }
        public int bookedTableId { get; set; }
        public int eventId { get; set; } 

        public TablesToBook()
        {
            tables = new List<Table>();
        }
    }
}

BookTable/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookTable.Database;
using BookTable.Models.DatabaseModels;
using BookTable.Models.ViewModels;
using Microsoft.AspNet.Identity.Owin;

namespace BookTable.Controllers
{
    public class TablesController : Controller
    {
        private ApplicationUserManager _userManager;

        public TablesController()
        {
        }

        public TablesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private BookTableContext db = new BookTableContext();

        // GET: Tables
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.Tables.ToList());
        }


        // GET: Tables/Details/5
        [Authorize(Roles = "User,Admin,Restaurant")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Table table = db.Tables.Find(id);
            var restaurantId = db.Tables.AsNoTracking().Include(d => d.Restaurant).Where(t => t.TableId == id).First().Restaurant.RestaurantId;
            ViewBag.RestId = restaurantId;

            if (table == null)
            {
                return HttpNotFound();
            }

            return View(table);
        }


        // GET: Tables/Create
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult Create([Bind(Include = "TableId,Seats,Avaliable")] Table table)
        {
            if (ModelState.IsValid)
            {
                db.Tables.Add(table);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(table);
        }

        // GET: Tables/Edit/5
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Tables.Find(id);
            var restaurantId = db.Tables.AsNoTracking().Include(d => d.Restaurant).Where(t => t.TableId == id).First().Restaurant.RestaurantId;
            ViewBag.RestId = restaurantId;
            if (table == null)
            {
                return HttpNotFound();
            }
            return View(table);
        }

        public ActionResult emptyTables()
        {
            return View();
        }

        // GET: Tables/tablesToBook/EventId
        [Authorize(Roles = "Admin, Restaurant,User")]
        public ActionResult tablesToBook(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var e = db.Events.Include(r => r.RestaurantId).Where(evnt => evnt.EventId == id).First();

            if (e == null)
            {
                return HttpNotFound();
            }

            var rest = db.Restaurants.Find(e.RestaurantId.RestaurantId);

            if (rest == null)
            {
                return HttpNotFound();
            }

            var reservations = db.Reservations.Where(r => r.Event.EventId == e.EventId).ToList();
            var restTables = db.Tables.Where(t => t.Restaurant.RestaurantId == rest.RestaurantId).ToList();
            bool flag = false;
            foreach(Table t in restTables)
            {
                flag = false;

                foreach(Reservation r in reservations)
                {
                    if(t.TableId == r.Table.TableId)
                    {
                        flag = true;
                        break;
                    }
                }

                if(flag)
                {
                    t.Avaliable = false;
                } else
                {
                    t.Avaliable = true;
                }

            }

            TablesToBook model = new TablesToBook();

            model.tables = restTables;
            model.restaurant = rest;
            model.eventId = (int)id;

            return View(model);
        }

        // GET: Tables/tablesForRestaurant/5
        [Authorize(Roles = "Admin, Restaurant, User")]
        public ActionResult tablesForRestaurant(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var tables = db.Tables.Where(tbl => tbl.Restaurant.RestaurantId == id ).ToList();
            ViewBag.RestId = id;

            if (tables == null)
            {
                return HttpNotFound();
            }

            return View(tables);
        }

        // GET: Tables/createTableForRestaurant/5
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult createTableForRestaurant(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var restaurant = db.Restaurants.Find(id);

            if (restaurant == null)
            {
                return HttpNotFound();
            }

            TableInRestaurant tableInRestaurant = new TableInRestaurant();
            tableInRestaurant.restaurantId = (int)id;

            return View(tableInRestaurant);
        }

        // POST: Tables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult createTableForRestaurant(TableInRestaurant tableRest)
        {
           
            if (ModelState.IsValid)
            {
                var restaurant = db.Restaurants.Find(tableRest.restaurantId);
                var tableInRest = tableRest.table;
                tableInRest.Restaurant = restaurant;
                db.Tables.Add(tableInRest);
                db.SaveChanges();
                return RedirectToAction("tablesForRestaurant", new { id = restaurant.RestaurantId });
            }

            return View(tableRest);
        }


        // POST: Tables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult Edit([Bind(Include = "TableId,Seats,Avaliable,Restaurant")] Table table)
        {
            if (ModelState.IsValid)
            {
                var restaurantId = db.Tables.AsNoTracking().Include(d => d.Restaurant).Where(t => t.TableId == table.TableId).First().Restaurant.RestaurantId;
               

                db.Entry(table).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("tablesForRestaurant", new { id = restaurantId });
            }
            return View(table);
        }

        // GET: Tables/Delete/5
        [Authorize(Roles = "Admin, Restaurant")]
        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Table table = db.Tables.Include(t => t.Restaurant).Where(t => t.TableId == id).First();

            Restaurant rest = db.Restaurants.Where(r => r.RestaurantId == table.Restaurant.RestaurantId).First();
            ViewBag.R = rest.RestaurantId;

            if (table == null)
            {
                return HttpNotFound();
            }

            try
            {
                var reservations = db.Reservations.Include(r => r.Table)
                    .Include(r => r.Event).Where(r => r.Table.TableId == table.TableId).ToList();
                bool canDelete = true;
                foreach (Reservation r in reservations)
                {
                    if (r.Event.Date > DateTime.Now)
                    {
                        canDelete = false;
                    }
                }

                if (canDelete)
                {

                    foreach (Reservation r in reservations)
                    {
                        db.Reservations.Remove(db.Reservations.Find(r.ReservationId));
                    }

                    db.Tables.Remove(table);
                    db.SaveChanges();
                    return RedirectToAction("tablesForRestaurant", new { id = rest.RestaurantId });
                }
                else
                {
                    return View("deleteFailed");
                }


            }
            catch (Exception e)
            {
                return View("deleteFailed"); ;
            }
        }

        // POST: Tables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Restaurant")]

BookTable/Views/Tables/Create.cshtml
@model BookTable.Models.DatabaseModels.Table

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Table</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Seats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Avaliable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Avaliable)
                    @Html.ValidationMessageFor(model => model.Avaliable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookTable/Views/Tables/Delete.cshtml
@model BookTable.Models.DatabaseModels.Table

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Table</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Seats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avaliable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avaliable)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to tables", "tablesForRestaurant", "Tables", new { id=ViewBag.RestId }, null)
        </div>
    }
</div>

BookTable/Views/Tables/Details.cshtml
@model BookTable.Models.DatabaseModels.Table

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Table</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Seats)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Avaliable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Avaliable)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TableId }) |
    @Html.ActionLink("Back to tables", "tablesForRestaurant", "Tables", new { id = ViewBag.RestId}, null)
</p>

BookTable/Views/Tables/Edit.cshtml
@model BookTable.Models.DatabaseModels.Table

@{
    ViewBag.Title = "Edit Table";
}

<h2>Edit your table</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TableId)

        <div class="form-group">
            @Html.LabelFor(model => model.Seats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seats, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="/Tables/tablesForRestaurant/@ViewBag.RestId"><button type="button" class="btn btn-secondary">Cancel</button></a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

BookTable/Views/Tables/Index.cshtml
@model IEnumerable<BookTable.Models.DatabaseModels.Table>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Seats)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Avaliable)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Seats)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Avaliable)
        </td>
        <td>
            @Html.ActionLink("Book", "bookATable", new { id = item.TableId }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.TableId }) |
            @Html.ActionLink("Details", "Details", new { id = item.TableId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.TableId })
        </td>
    </tr>
}

</table>

BookTable/Views/Tables/createTableForRestaurant.cshtml
@model BookTable.Models.ViewModels.TableInRestaurant


@{
    ViewBag.Title = "Add a table";
}


<h4>Add a table</h4>

@using (Html.BeginForm(FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.table.Seats, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.table.Seats, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.table.Seats, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.restaurantId)
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <a href="/Tables/tablesForRestaurant/@Model.restaurantId"><button type="button" class="btn btn-secondary">Cancel</button></a>
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
}

BookTable/Views/Tables/deleteFailed.cshtml
@{
    ViewBag.Title = "Delete failed";
}

<div style="text-align:center" class="mb-5">
    <img style="width:20%" src="https://koenig-media.raywenderlich.com/uploads/2018/11/monster_annoyed2-320x320.png">
    <div style="width:50%;" class="ml-auto mr-auto">
        <h4 style="color:gray">You cannot delete your table because there are active reservations for future event!</h4>
        <p style="color:gray">Wait until event is finished and than delete your table...</p>
    </div>
    <a href="/Tables/tablesForRestaurant/@ViewBag.R"><button class="btn btn-secondary mt-3">Back</button></a>
</div>

BookTable/Views/Tables/emptyTables.cshtml
@{
    ViewBag.Title = "Empty tables";
}

<div style="text-align:center" class="mb-5">
    <img style="width:20%" src="https://www.pinclipart.com/picdir/big/33-338965_luncheon-clipart-thanksgiving-plate-fork-and-knife-clipart.png">
    <div style="width:50%;" class="ml-auto mr-auto">
        <h4 style="color:gray">There are no tables provided from restaurant!</h4>
        <p style="color:gray">Wait until restaurant provide tables for booking...</p>
    </div>
    <a href="/Restaurants/Index"><button class="btn btn-secondary mt-3">Back</button></a>
</div>

BookTable/Views/Tables/tablesForRestaurant.cshtml
@model IEnumerable<BookTable.Models.DatabaseModels.Table>

@{
    ViewBag.Title = "My Tables";
}

@if (Model.Count() > 0)
{

    <div class="ml-auto mr-auto" style="width:50%">
        <h2>My Tables</h2>


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Seats)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Seats)
                    </td>
                    <td style="text-align:end">
                        <a class="btn btn-secondary" href="/Tables/Edit/@item.TableId">Edit</a>
                        <a data-toggle="modal" data-target="#exampleModal" class="btn btn-danger text-white">Delete</a>
                    </td>
                </tr>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Your table wiil be deleted</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h6>Are you sure that you want to delete your table?</h6>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <a class="btn btn-danger" href="/Tables/Delete/@item.TableId">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </table>
        <div class="mb-5">
            <a href="/Restaurants/Details/@ViewBag.RestId"><button type="button" class="btn btn-secondary">Back</button></a>
            <a href="/Tables/createTableForRestaurant/@ViewBag.RestId"><button type="button" class="btn btn-success">New Table</button></a>
        </div>
    </div>
}
else
{
    <div style="text-align:center" class="mb-5">
        <div>
            <h4 style="color:gray">There are no tables added!</h4>
            <p style="color:gray">Please add your tables for restaurant</p>
            <img style="width:20%" src="https://www.stickpng.com/assets/thumbs/584f07ef6a5ae41a83ddee55.png">
        </div>
        <a href="/Tables/createTableForRestaurant/@ViewBag.RestId"><button class="btn btn-success mt-1">Add</button></a>
    </div>


}

BookTable/Views/Tables/tablesToBook.cshtml
@model BookTable.Models.ViewModels.TablesToBook


@{
    ViewBag.Title = "Book";
}


@section head{
    <style type="text/css">
        body {
            background-color: lightgray;
        }
    </style>
    <link href="~/Style/About.css" rel="stylesheet" />
    @Styles.Render("~/Content/fontawesome")
}
<div class="row">
    <div class="col-4">

        @if (Model.tables.Count() > 0)
        {
            <h2><span>Tables to book</span></h2>

            <div style="display: inline-block" class="mt-4">
                <div style="width: 400px; display:inline-block">
                    @foreach (var item in Model.tables)
                    {
                        if (item.Avaliable)
                        {
                            using (Html.BeginForm("makeReservation", "Reservations", new { id = item.TableId }, FormMethod.Post, new { style = "display: inline-block;" }))
                            {
                                @Html.HiddenFor(model => model.eventId)
                                <button type="submit" class="btn btn-secondary border-0 rounded-circle mr-2 mb-2" style="width: 100px; height: 100px;"><span style="font-size: 20pt">@item.Seats</span><br />seats</button>
                            }
                        }
                        else
                        {
                            <button disabled class="btn btn-secondary border-0 rounded-circle mr-2 mb-2" style="width: 100px; height: 100px;"><span style="font-size: 20pt">@item.Seats</span><br />seats</button>
                        }
                    }
                </div>
            </div>
        }
        else
        {
            <div style="text-align:center" class="mb-5">
                <div>
                    <h4 style="color:gray">There are no tables provided from restaurant!</h4>
                    <p style="color:gray">Please wait until restaurant provide tables for booking...</p>
                    <img style="width:90%" src="https://www.stickpng.com/assets/thumbs/584f07ef6a5ae41a83ddee55.png">
                </div>
                <a href="/Events/Index"><button class="btn btn-secondary mt-4">Back</button></a>
            </div>



        }
    </div>
    <div class="col-8" style="width:600px; display:inline-block">
        <img class="img-fluid" src="https://www.adlers-innsbruck.com/fileadmin/_processed_/6/4/csm_restaurant-img-02_d666f4932c.jpg" />
    </div>
</div>